services:
  shilnk:
    image: shlinkio/shlink
    container_name: shlink
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - shlink-db
    environment:
      - DEFAULT_DOMAIN=mydomain.com
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=postgres
      - DB_USER=shlink
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=shlink-db
      - INITIAL_API_KEY=${API_KEY}
      - TIMEZONE=Asia/Bangkok #Find your timezone here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
    networks:
      - proxy
      - backend
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.shlink.entrypoints=https-external"
      - "traefik.http.routers.shlink.rule=Host(`s.mydomain.com`)"
      - "traefik.http.routers.shlink.tls=true"


  shlink-db:
    image: postgres:16-alpine
    container_name: shlink-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=shlink
      - POSTGRES_DB=shlink
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

networks:
  proxy:
    name: proxy
    external: true
  backend:

volumes:
  db: