services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    group_add:
      - "105" # Change this to match your "render" host group id and remove this comment
    ports:
      - 8096:8096/tcp #for local use so the traffic doesn't have to pass through traefik
      # - 8920:8920/tcp
      # - 1900:1900/udp
      # - 7359:7359/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro #timezone
      - path/to/config:/config
      - path/to/cache:/cache
      - path/to/media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 #Change this to match your gpu
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=https-external"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.mydomain.com`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.scheme=http"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

networks:
  proxy:
    name: proxy
    external: true
