name: portainer

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
#    command: --log-level DEBUG #For debuging, somehow this isn't in official document.
    volumes:
      - data:/data
      - /etc/localtime:/etc/localtime:ro #timezone
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local.mydomain.com`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.scheme=https"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
      - "traefik.http.routers.portainer.middlewares=lan-whitelist@file"

networks:
  proxy:
    name: proxy
    external: true

volumes:
    data: